### ISSUE TITLE
2022-5-16 手机端调用登陆接口报错

### ISSUE THREAD

**Issue by wangxiang3** [steedos/steedos-project-ruihui#34]
手机端登陆用了/accounts/password/login这个接口，但今天突然登不上了，后台报错信息如下
Error: accounts.invalid_credentials
    at AccountsPassword.<anonymous> (/Users/pastic/security-platform/node_modules/@steedos/accounts/src/password/accounts-password.ts:755:13)
    at step (/Users/pastic/security-platform/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/pastic/security-platform/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/pastic/security-platform/node_modules/tslib/tslib.js:114:62)
    at /Users/pastic/security-platform/node_modules/meteor-promise/fiber_pool.js:43:39。

web登陆是正常的，看了下web端的登陆请求数据，发现密码好像是加密过的，我的密码本来是123456，加密过后是8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92，我把这个加密过的复制到手机端就能登上了。

**Comment by wangxiang3** [comment]
请问是加密过的吗？如果是的话，加密方式是怎样的。

**Comment by wangxiang3** [comment]
![截屏2022-05-30 下午1 18 26](https://user-images.githubusercontent.com/72076955/170921986-fd82bd03-4f33-4703-b08c-46b257ca5726.png)

**Comment by wangxiang3** [comment]
sha256加密
